name = "iss-urine-api"
main = "src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "URINE_TRACKER", class_name = "UrineTracker" }
]

[[migrations]]
tag = "v1"
new_classes = ["UrineTracker"]
